project/apps/login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('roles/', views.roles, name='roles'),
    path('teacher/login/', views.Tlogin, name='Tlogin'),
    path('student/login/', views.Slogin, name='Slogin'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('', include('apps.login.urls')),
    path('', include('apps.student_panel.urls')),
    path('teacher/', include('apps.teacher_panel.urls')),
    path('captcha/', include('captcha.urls')),

]
handler404 = 'apps.home.views.custom_404_view'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl" class="overflow-x-hidden">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>attendance-system</title>
    <link rel="stylesheet" href="{% static 'css/output.css' %}">
{% block head-style %}{% endblock %}
</head>

{% block background %}{% endblock %}

{% block header %}{% endblock %}

{% block content %}{% endblock %}

{% include 'footer.html' %}

{% block section %}{% endblock %}

</body>
</html>

project/templates/footer.html
{% load static %}
<!--footer-->
<footer class="bg-[#0A2342] text-white pt-5 md:pt-10 mt-20">

  <div class="container mx-auto px-4 mt-8">
    <div class="grid grid-cols-4 gap-4">

      <div class="hidden md:block text-center p-4 border-l-[1px] border-gray-500">
        <h4 class="font-bold text-2xl mb-6">اطلاعات تماس</h4>
        <p class="mb-6">بین کلاهدوز ۴ و ۶</p>
        <p class="mb-6">۰۵۱۳۸۴۰۱۴۱۳</p>
        <p>sadi@gmail.com</p>
      </div>

      <div class="hidden md:block text-center p-4 border-l-[1px] border-gray-500">
        <h4 class="font-bold text-2xl mb-6">لینک‌های مفید</h4>
        <a href="{% url 'login:roles' %}" class="block mb-6 hover:text-gray-300">ورود</a>
        <a href="#about-school" class="block mb-6 hover:text-gray-300">درباره ما</a>
        <a href="#about_system" class="block mb-6 hover:text-gray-300">راهنمای کاربری</a>
      </div>

      <div class="hidden md:block text-center p-4 border-l-[1px] border-gray-500">
        <h4 class="font-bold text-2xl mb-6">لینک‌های مرتبط</h4>
        <a href="https://shad.ir/sadiisampad1402" class="block mb-6 hover:text-gray-300">هنرستان سمپاد سعدی</a>
        <a href="#" class="block mb-6 hover:text-gray-300">اداره کل سمپاد</a>
        <a href="#" class="block hover:text-gray-300">آموزش و پرورش ناحیه ۳</a>
      </div>

      <div class="hidden md:flex flex-col items-center justify-center p-4 space-y-6">
        <img src="{% static './pics/logo.png' %}" class="w-40 h-40 object-contain" alt="لوگو هنرستان">
        <img src="{% static './pics/shad.png' %}" class="w-30 h-30 object-contain" alt="لوگو سمپاد">
      </div>
    </div>
  </div>

  <div class="md:hidden grid grid-cols-2 gap-0">
    <!-- بخش اطلاعات تماس -->
    <div class="text-center sm:text-right p-5 border-l sm:border-none border-gray-500">
      <h4 class="font-bold text-xl mb-6">اطلاعات تماس</h4>
      <p class="mb-4">بین کلاهدوز ۴ و ۶</p>
      <p class="mb-4">۰۵۱۳۸۴۰۱۴۱۳</p>
      <p>sadi@gmail.com</p>
    </div>
    <!-- بخش لوگوها -->
    <div class="flex flex-col items-center justify-center p-4 gap-5 ">
      <img src="{% static './pics/logo.png' %}" class="w-24 h-24 object-contain" alt="لوگو هنرستان">
      <img src="{% static './pics/shad.png' %}" class="w-24 h-24 object-contain" alt="لوگو سمپاد">
    </div>
  </div>

    </div>
  <div class="bg-[#FF7F50] h-full w-full mt-10">
    <p class="text-center p-2 hidden md:block">تمامی حقوق این سایت متعلق به هنرستان دخترانه فنی و حرفه‌ای استعدادهای درخشان سعدی است</p>
    <p class="text-center p-2 md:hidden text-sm">تمامی حقوق این سایت متعلق به هنرستان دخترانه سمپاد سعدی است.</p>
  </div>
</footer>