project/apps/login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('roles/', views.roles, name='roles'),
    path('teacher/login/', views.Tlogin, name='Tlogin'),
    path('student/login/', views.Slogin, name='Slogin'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('', include('apps.login.urls')),
    path('', include('apps.student_panel.urls')),
    path('teacher/', include('apps.teacher_panel.urls')),
    path('captcha/', include('captcha.urls')),

]
handler404 = 'apps.home.views.custom_404_view'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/login/models.py
from django.db import models
from django.contrib.auth.models import User


class classes(models.Model):
    class_id = models.IntegerField(primary_key=True)
    class_name = models.CharField(max_length=100)
    grade = models.CharField(max_length=100)

    def __str__(self):
        return  str(self.class_id)

class students(models.Model):
    student_id = models.CharField(max_length=20, primary_key=True)
    student_name = models.CharField(max_length=100)
    student_lname = models.CharField(max_length=100)
    class_id = models.ForeignKey(classes , on_delete=models.CASCADE)

    def __str__(self):
        return self.student_name

class teachers(models.Model):
    teacher_id = models.IntegerField(primary_key=True)
    teacher_name = models.CharField(max_length=100)
    teacher_lname = models.CharField(max_length=100)
    def __str__(self):
        return self.teacher_name

class subjects(models.Model):
    subject_id = models.IntegerField(primary_key=True)
    subject_name = models.CharField(max_length=100)
    def __str__(self):
        return self.subject_name

class teacher_class_subject(models.Model):
    teacher_class_subject_id = models.IntegerField(primary_key=True)
    teacher_id = models.ForeignKey(teachers, on_delete=models.CASCADE)
    class_id = models.ForeignKey(classes, on_delete=models.CASCADE)
    subject_id = models.ForeignKey(subjects , on_delete=models.CASCADE)
    def __str__(self):
        return str(self.teacher_class_subject_id)

class attendance(models.Model):
    attendance_id = models.AutoField(primary_key=True)
    student_id = models.ForeignKey(students , on_delete=models.CASCADE)
    class_id = models.ForeignKey(classes , on_delete=models.CASCADE)
    subject_id = models.ForeignKey(subjects , on_delete=models.CASCADE, null=True, blank=True)  # میتونی به دلخواه پر یا خالی باشه
    teacher_id = models.ForeignKey(teachers , on_delete=models.CASCADE)
    date = models.DateField()  # تغییر داده شده به DateField
    status_choice = (
        ('a', 'absent'),
        ('p', 'present'),
        ('l', 'late')
    )
    status = models.CharField(max_length=1, choices=status_choice)
    proof_image = models.ImageField(upload_to='attendance/images/', null=True, blank=True)
    proof_verified = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return self.get_status_display()

project/apps/login/forms.py
from django import forms
from captcha.fields import CaptchaField, CaptchaTextInput


class SLoginForm(forms.Form):
    st_code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'w-full px-4 py-1 md:py-3 text-lg border border-gray-300 md:rounded-2xl rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white/90',
        'placeholder': 'کد ملی خود را به طور کامل وارد کنید'}))
    st_password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'w-full px-4 py-1 md:py-3 text-lg border border-gray-300 md:rounded-2xl rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white/90',
            'placeholder': 'رمز عبور شما همان کد ملی شما می باشد',
        })
    )
    captcha = CaptchaField(
        widget=CaptchaTextInput(attrs={
            'class': 'px-4 py-2 md:py-3 text-lg border border-gray-300 md:rounded-2xl rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white/90 w-full',
            'placeholder': 'کد امنیتی را وارد کنید',
        })
    )

class TLoginForm(forms.Form):
    teacher_code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'col-span-9 px-4 py-2 md:py-3 text-lg border border-gray-300 md:rounded-2xl rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white/90',
        'placeholder': 'کد پرسنلی خود را به طور کامل وارد کنید'}))
    teacher_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'col-span-9 px-4 py-2 md:py-3 text-lg border border-gray-300 md:rounded-2xl rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white/90',
        'placeholder': 'رمز عبور شما همان کد پرسنلی شما می باشد'}))
    captcha = CaptchaField(widget=CaptchaTextInput(attrs={
        'class': 'w-full px-4 py-2 md:py-3 text-lg border border-gray-300 md:rounded-2xl rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white/90',
        'placeholder': 'کد امنیتی را وارد کنید',
    }))

project/apps/login/views.py
from django.shortcuts import render, redirect
from .forms import SLoginForm , TLoginForm
from .models import students , teachers

def roles(request):
    return render(request, 'login/roles.html')

def Tlogin(request):
    form = TLoginForm(request.POST or None)
    error_message = None
    if request.method == 'POST':
        if form.is_valid():
            code = form.cleaned_data['teacher_code'].strip()
            password = form.cleaned_data['teacher_password'].strip()
            if code == password:
                try:
                    teacher = teachers.objects.get(teacher_id=code)
                    request.session['teacher_id'] = teacher.teacher_id
                    return redirect('teacher_panel:panel')
                except teachers.DoesNotExist:
                    error_message = 'معلمی با این کد پرسنلی یافت نشد.'
            else:
                error_message = 'کد ملی و رمز عبور باید یکسان باشند.'

    return render(request, 'login/teacher.html', {'form': form, 'error_message': error_message})

def Slogin(request):
    form = SLoginForm(request.POST or None)
    error_message = None

    if request.method == 'POST':
        if form.is_valid():
            code = form.cleaned_data['st_code']
            password = form.cleaned_data['st_password']
            if code == password:
                try:
                    student = students.objects.get(student_id=code)
                    request.session['student_id'] = student.student_id
                    return redirect('student_panel:panel')
                except students.DoesNotExist:
                    error_message = 'دانش‌آموزی با این کد ملی یافت نشد.'
            else:
                error_message = 'کد ملی و رمز عبور باید یکسان باشند.'

    return render(request, 'login/student.html', {'form': form, 'error_message': error_message})

project/apps/login/templates/login/roles.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl" class="overflow-x-hidden">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>sign in</title>
<link rel="stylesheet" href="{% static 'css/output.css' %}">
  <style>
  body {
      overflow-x: hidden;
      background-image: url({% static './pics/bg-triangle.png' %});
      background-repeat: no-repeat;
      background-size: cover;
      background-position: top;
    }

    @media (max-width: 768px) {
      body {
        background-image: url({% static './pics/bg-triangle2.png' %});
        background-size: cover; 
        background-position: center top; 
      }
    }
  </style>
</head>

<body class="relative overflow-x-hidden font-yekan bg-gray-100 min-h-screen flex items-center justify-center p-4">
  <div class="bg-[#0A2342] rounded-2xl shadow-xl w-full max-w-5xl overflow-hidden">
    
    <div class="flex flex-col md:flex-row">
      <!-- بخش انتخاب نقش -->
      <div class="w-full md:w-1/2 p-8 md:p-12 flex flex-col items-center justify-center">
          <h2 class="text-2xl md:text-4xl font-bold text-white text-center mb-8 md:mb-12 md:leading-loose leading-loose">
               نقش خود را برای ورود انتخاب کنید
             </h2>
        
        <div class="flex flex-col gap-5 md:gap-8 w-full items-center">
          <a href="{% url 'login:Slogin' %}" class="w-[85%] h-20 bg-[#FF7F50] text-white flex items-center justify-center rounded-xl shadow-lg text-xl hover:bg-[#FF7F50]/80 transition duration-300">
            دانش‌آموز
          </a>
          
          <a href="{% url 'login:Tlogin' %}" class="w-[85%] h-20 bg-[#FF7F50] text-white flex items-center justify-center rounded-xl shadow-lg text-xl hover:bg-[#FF7F50]/80 transition duration-300">
            معلم
          </a>
          
          <a href="manager.html" class="w-[85%] h-20 bg-[#FF7F50] text-white flex items-center justify-center rounded-xl shadow-lg text-xl hover:bg-[#FF7F50]/80 transition duration-300">
            معاون / مدیر
          </a>
        </div>
      </div>

      <div class="hidden md:flex md:w-[90%] bg-[#0A2342] items-center justify-center p-2">
        <img src="{% static './pics/man.png' %}" alt="تصویر راهنما"
             class="w-full h-auto min-h-[600px] object-contain">
      </div>
    </div>
  </div>
</body>
     </html>

project/apps/login/templates/login/student.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>S-login</title>
    <link href="{% static 'css/output.css' %}" rel="stylesheet"/>
    <style>
           img.captcha {
            height: 38px !important;
            width: 20% !important;
        }

        @media (min-width: 768px) {
            img.captcha {
                height: 50px !important;
                width: 15% !important;
            }
        }
    </style>
</head>

<body class="min-h-screen p-0 font-yekan bg-gray-100 bg-no-repeat bg-top bg-contain md:bg-cover">

<div class="hidden md:block fixed inset-0 -z-10 bg-no-repeat bg-cover bg-top"
     style="background-image: url({% static './pics/bg-triangle.png' %});"></div>
<div class=" md:hidden fixed inset-0 -z-10 bg-no-repeat bg-cover bg-top"
     style="background-image: url({% static './pics/bg-triangle2.png' %});"></div>

<section class="w-full min-h-screen flex items-center justify-center p-4 relative">

    <!-- Corner Imgs -->
    <img src="{% static 'pics/t-l.png' %}" class="top-0 left-0 hidden md:block absolute">
    <img src="{% static 'pics/b-r.png' %}" class="hidden md:block absolute bottom-0 right-0 ">

    <!-- Login Form -->
    <div class="bg-[#0A2342] rounded-2xl shadow-xl w-full max-w-3xl md:min-h-[700px] h-[500px] flex flex-col justify-center items-center">

        <h1 class="text-xl md:text-5xl font-bold text-center text-white md:mb-20 mb-10">ورود دانش آموز</h1>
        <form class="md:space-y-10 space-y-5 w-[90%] md:w-[80%]" method="post">
            {% if error_message %}
                <p style="color:red;">{{ error_message }}</p>
            {% endif %}
            {% csrf_token %}
            <div class="flex flex-row gap-6 ">
                <label for="national-code" class="block text-white mb-3 text-xl md:text-2xl text-nowrap">کد ملی:</label>
                {{ form.st_code }}
            </div>

            <div class="flex flex-row gap-5">
                <label for="password" class="block text-white mb-3 text-xl md:text-2xl l text-nowrap">رمز عبور:</label>
                {{ form.st_password }}
            </div>

            <div>
{#                <label for="captcha" class="block text-white mb-3 text-xl md:text-2xl text-nowrap">کد امنیتی:</label>#}
                     <div class="col-span-9 flex items-center md:gap-4 gap-6">
                    {{ form.captcha.image }}
                    {{ form.captcha }}
                </div>

            <div class="flex flex-row gap-4">
                <button
                        type="submit"
                        class="w-full bg-[#FF7F50] text-[#0A2342] py-3 px-4 rounded-2xl hover:bg-[#3BD1A4] hover:text-white transition duration-200 mt-8 text-xl md:text-2xl ">
                    ورود
                </button>
                <button
                        onclick="history.back()"
                        type="button"
                        class="w-full bg-[#FF7F50] text-[#0A2342] py-3 px-4 rounded-2xl hover:bg-[#3BD1A4] hover:text-white transition duration-200 mt-8 text-xl md:text-2xl ">
                    بازگشت
                </button>

            </div>
        </form>
    </div>
    </div>
</section>
</body>
</html>

project/apps/login/templates/login/teacher.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>T-login</title>
    <link href="{% static 'css/output.css' %}" rel="stylesheet"/>
    <style>
        img.captcha {
            height: 38px !important;
            width: 20% !important;
        }

        @media (min-width: 768px) {
            img.captcha {
                height: 50px !important;
                width: 20% !important;
            }
        }
    </style>
</head>

<body class="min-h-screen p-0 font-yekan bg-gray-100">
<div class="hidden md:block fixed inset-0 -z-10 bg-no-repeat bg-cover bg-top"
     style="background-image: url({% static './pics/bg-triangle.png' %});"></div>
<div class=" md:hidden fixed inset-0 -z-10 bg-no-repeat bg-cover bg-top"
     style="background-image: url({% static './pics/bg-triangle2.png' %});"></div>

<section class="w-full min-h-screen flex items-center justify-center p-4 relative">

    <!-- Corner Imgs -->
    <img src="{% static 'pics/bag.png' %}" class="top-0 left-0 hidden md:block absolute">
    <img src="{% static 'pics/pen.png' %}" class="hidden md:block absolute bottom-0 right-0 ">

    <!-- Login Form -->
    <div class="bg-[#0A2342] rounded-2xl shadow-xl w-full max-w-3xl md:min-h-[700px] h-[450px] flex flex-col justify-center items-center">

        <h1 class="text-xl md:text-5xl font-bold text-center text-white md:mb-20 mb-10">ورود معلم</h1>
        <form class="md:space-y-10 space-y-5 w-[90%] md:w-[80%]" method="post">
            {% if error_message %}
                <p style="color:red;">{{ error_message }}</p>
            {% endif %}
            {% csrf_token %}
            <div class="grid grid-cols-12 items-center gap-2">
                <label for="national-code" class="col-span-3 text-white text-lg md:text-2xl text-right">کد
                    پرسنلی:</label>
                {{ form.teacher_code }}
            </div>

            <div class="grid grid-cols-12 items-center gap-2">
                <label for="password" class="col-span-3 text-white text-lg md:text-2xl text-right">رمز عبور:</label>
                {{ form.teacher_password }}
            </div>
            <div>
                {#                <label for="captcha" class="block text-white mb-3 text-xl md:text-2xl text-nowrap">کد امنیتی:</label>#}
                <div class="col-span-9 flex items-center md:gap-8 gap-6">
                    {{ form.captcha.image }}
                    {{ form.captcha }}
                </div>
            </div>


            <div class="w-[100%] flex flex-row gap-4 justify-center items-center  mx-auto">
                <button
                        type="submit"
                        class="w-full bg-[#FF7F50] text-[#0A2342] py-3 px-4 md:rounded-2xl rounded-xl hover:bg-[#3BD1A4] hover:text-white transition duration-200 mt-8 text-xl md:text-2xl ">
                    ورود
                </button>
                <button
                        onclick="history.back()"
                        type="button"
                        class="w-full bg-[#FF7F50] text-[#0A2342] py-3 px-4 md:rounded-2xl rounded-xl  hover:bg-[#3BD1A4] hover:text-white transition duration-200 mt-8 text-xl md:text-2xl ">
                    بازگشت
                </button>

            </div>
        </form>
    </div>
    </div>
</section>
</body>
</html>