project/apps/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    # path('404/', views.ss404, name='ss404'),
]

project/apps/student_panel/urls.py
from django.urls import path
from . import views

app_name = 'student_panel'
urlpatterns = [
     path('student/panel/', views.panel, name='panel'),
     path('logout/', views.logout, name='logout'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('', include('apps.login.urls')),
    path('', include('apps.student_panel.urls')),
    path('teacher/', include('apps.teacher_panel.urls')),
    path('captcha/', include('captcha.urls')),

]
handler404 = 'apps.home.views.custom_404_view'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/student_panel/models.py
from django.db import models

from apps.login.models import classes , students , teachers , subjects , teacher_class_subject , attendance

project/apps/student_panel/views.py
from datetime import datetime, date, timedelta
from django.db.models import Q
from django.shortcuts import render, redirect
from apps.login.models import attendance, students, teachers, subjects, teacher_class_subject
import jdatetime
from django.contrib import messages
from datetime import datetime, date


def panel(request):
    student_id = request.session.get('student_id')
    if not student_id:
        return redirect('login:Slogin')

    try:
        student = students.objects.get(student_id=student_id)
    except students.DoesNotExist:
        return redirect('login:Slogin')

    selected_teacher = request.GET.get('teacher_id')
    selected_subject = request.GET.get('subject_id')
    selected_date = request.GET.get('date')

    class_id = student.class_id
    tcs = teacher_class_subject.objects.filter(class_id=class_id)

    subjects_list = list(subjects.objects.filter(subject_id__in=tcs.values_list('subject_id', flat=True).distinct()))
    # teachers_list = list(teachers.objects.filter(teacher_id__in=tcs.values_list('teacher_id', flat=True).distinct()))

    # تاریخ‌ها
    date_range = []
    today = date.today()
    start_date = date(2025, 3, 20)
    current_date = start_date
    while current_date <= today:
        date_range.append({
            'gregorian': current_date.strftime('%Y-%m-%d'),
            'jalali': jdatetime.date.fromgregorian(date=current_date).strftime('%Y/%m/%d')
        })
        current_date += timedelta(days=1)
    date_range.reverse()


    absences = attendance.objects.filter(student_id=student, status='a')

    # if selected_teacher:
    #     try:
    #         absences = absences.filter(teacher_id=int(selected_teacher))
    #     except ValueError:
    #         pass

    if selected_subject:
        try:
            absences = absences.filter(subject_id=selected_subject)
        except (ValueError, TypeError):
            pass

    if selected_date:
        try:
            gdate = datetime.strptime(selected_date, '%Y-%m-%d').date()
            absences = absences.filter(date=gdate)
        except ValueError:
            pass

    if request.method == "POST":
        for key, uploaded_file in request.FILES.items():
            if key.startswith("proof_"):
                parts = key.split("_")
                if len(parts) == 2 and parts[1].isdigit():
                    attendance_id = int(parts[1])
                    try:
                        absence = attendance.objects.get(attendance_id=attendance_id, student_id=student)
                        absence.proof_image = uploaded_file
                        absence.save()
                    except attendance.DoesNotExist:
                        pass

    def get_jalali_date(gdate):
        if isinstance(gdate, (datetime, date)):
            jdate = jdatetime.date.fromgregorian(date=gdate)
            return jdate.strftime('%Y/%m/%d'), jdate.strftime('%A')
        return '', ''

    absences_with_jalali = []
    for a in absences.order_by('-date'):
        jalali_date, weekday = get_jalali_date(a.date)
        absences_with_jalali.append({
            'attendance_id': a.attendance_id,
            'proof_image': a.proof_image,
            'proof_verified': a.proof_verified,
            'subject_name': a.subject_id.subject_name if a.subject_id else '',
            'jalali_date': jalali_date,
            'weekday': weekday,
        })
    no_records = len(absences_with_jalali) == 0


    return render(request, 'panel/student.html', {
        'absences': absences_with_jalali,
        'subjects_list': subjects_list,
        # 'teachers_list': teachers_list,
        'date_range': date_range,
        # 'upload_message': upload_message,
        'first_name': student.student_name,
        'last_name': student.student_lname,
        'selected_teacher': selected_teacher,
        'selected_subject': selected_subject,
        'selected_date': selected_date,
        'no_records': no_records,
    })


def logout(request):
    request.session.flush()
    return render(request, 'home/index.html', {'messages': ['شما با موفقیت خارج شدید.']})

project/apps/student_panel/templates/panel/student.html
{% extends 'base.html' %}
{% load static %}

{# head style #}
{% block head-style %}
    <style>
        body {
            overflow-x: hidden;
        }

        @layer utilities {
            .animate-slide-up {
                animation: slide-up 0.5s ease-out forwards;
            }

            .animate-slide-down {
                animation: slide-down 0.5s ease-out forwards;
            }

            @keyframes slide-up {
                0% {
                    transform: translateX(100%);
                    opacity: 0;
                }
                100% {
                    transform: translateX(0);
                    opacity: 1;
                }
            }

            @keyframes slide-down {
                0% {
                    transform: translateX(0);
                    opacity: 1;
                }
                100% {
                    transform: translateX(100%);
                    opacity: 0;
                }
            }
        }
    </style>
{% endblock %}

{# header #}
{% block header %}

    <body class="font-yekan">

    {% if upload_message %}
        <div class="fixed top-2 right-2 z-50 space-x-2 space-y-2">
            {% for msg in upload_message %}
                <div id="message-{{ forloop.counter }}"
                     class="animate-slide-up  text-[#FF7F50] font-bold mx-auto w-max">
                    {{ msg }}
                </div>
            {% endfor %}
        </div>

        <script>
            document.addEventListener('DOMContentLoaded', () => {
                {% for message in messages %}
                    setTimeout(() => {
                        const msg = document.getElementById('message-{{ forloop.counter }}');
                        if (msg) {
                            msg.classList.add('animate-slide-down');
                            msg.addEventListener('animationend', () => msg.remove());
                        }
                    }, 3000);
                {% endfor %}
            });
        </script>
    {% endif %}


    <section class="bg-hero w-screen min-h-screen bg-no-repeat bg-cover bg-center pt-5 md:pt-10">
    <header class=" bg-[#0A2342] text-white rounded-2xl shadow-md md:max-w-[70%] max-w-[95%]  font-yekan mx-auto">
        <div class="px-6 py-4 flex items-center justify-center">
            <div class="flex items-center space-x-10 space-x-reverse">
                <img src="{% static './pics/user.png' %}" class="md:max-w-16 md:max-h-16  max-h-10 max-w-10"
                     alt="لوگو"/>
                <nav class="flex md:gap-20 gap-10 sm:text-base ">
                    <p class="hover:text-gray-300 text-lg md:text-2xl hidden md:block">دانش
                        آموز {{ first_name }} {{ last_name }} به پنل کاربری خوش
                        آمدید</p>
                    <a href="{% url 'home:home' %}" class="hover:text-gray-300 text-lg md:text-2xl text-nowrap">صفحه
                        اصلی</a>
                    <a href="{% url 'student_panel:logout' %}"
                       class="hover:text-gray-300 text-lg md:text-2xl text-nowrap">خروج</a>
                </nav>
            </div>
    </header>
{% endblock header %}

{# content #}
{% block content %}
    <div class=" md:p-10 flex justify-center items-center">
        <div class="bg-white rounded-lg p-4 md:p-6 flex flex-row items-center gap-6 md:gap-12 w-full max-w-6xl">

            <div class="w-full flex flex-row justify-center gap-4 md:gap-8 p-4 md:p-6">
                <form method="get" id="filter-form" class="flex gap-4 md:gap-8">
                    <h2 class="text-xl md:text-3xl font-bold text-gray-800 mb-4 md:mb-0 hidden md:block">فیلترها:</h2>
                    <!-- دروس -->
                    <div class="w-full flex flex-row">
                        <select name="subject_id" onchange="document.getElementById('filter-form').submit()"
                                class="max-w-[260px] min-w-[50px] px-4 py-2 bg-[#FF7F50] text-white rounded-xl
                                   focus:outline-none focus:ring-2 focus:ring-blue-500
                                   text-xs md:text-2xl text-right appearance-none text-wrap">
                            <option value=""> درس</option>
                            {% for subject in subjects_list %}
                                <option value="{{ subject.subject_id }}"
                                        {% if selected_subject == subject.subject_id|stringformat:"s" %}selected{% endif %}>
                                    {{ subject.subject_name }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>

                    <!-- تاریخ -->
                    <div class="w-full flex flex-row">
                        <select name="date" onchange="document.getElementById('filter-form').submit()"
                                class="max-w-[260px] min-w-[50px] px-4 py-2 bg-[#FF7F50] text-white rounded-xl
                                   focus:outline-none focus:ring-2 focus:ring-blue-500
                                   text-xs md:text-2xl text-right appearance-none text-wrap">
                            <option value=""> تاریخ</option>
                            {% for d in date_range %}
                                <option value="{{ d.gregorian }}"
                                        {% if selected_date == d.gregorian|stringformat:"s" %}selected{% endif %}>
                                    {{ d.jalali }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>

                    <!-- دبیران -->
                    {#                    <div class="w-full flex flex-row">#}
                    {#                        <select name="teacher_id" onchange="document.getElementById('filter-form').submit()"#}
                    {#                                class="max-w-[260px] min-w-[50px] px-4 py-2 bg-[#FF7F50] text-white rounded-xl#}
                    {#                                   focus:outline-none focus:ring-2 focus:ring-blue-500#}
                    {#                                   text-xs md:text-2xl text-right appearance-none text-wrap">#}
                    {#                            <option value="">دبیران</option>#}
                    {#                            {% for teacher in teachers_list %}#}
                    {#                                <option value="{{ teacher.teacher_id }}"#}
                    {#                                        {% if selected_teacher == teacher.teacher_id|stringformat:"s" %}selected{% endif %}>#}
                    {#                                    {{ teacher.teacher_name }} {{ teacher.teacher_lname }}#}
                    {#                                </option>#}
                    {#                            {% endfor %}#}
                    {#                        </select>#}
                    {#                    </div>#}

                </form>
            </div>
        </div>
    </div>

    <!-- table -->
    <div class="w-full flex justify-center px-4">
        {% if absences %}
            <div class="w-full max-w-6xl bg-white rounded-xl shadow-lg overflow-hidden">

                <table class="w-full text-center font-yekan text-lg">
                    <thead>
                    <tr class="bg-[#FBFBFB] md:text-xl text-base">
                        <th class="py-8">درس</th>
                        <th class="py-8">روز هفته</th>
                        <th>تاریخ</th>
                        <th>آپلود گواهی</th>
                        <th>تایید گواهی</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for absence in absences %}

                        <tr class="bg-[#EBEBEB] odd:bg-gray-100 md:text-lg text-sm">
                            <td class="py-4">{{ absence.subject_name }}</td>
                            <td class="py-4">{{ absence.weekday }}</td>
                            <td>{{ absence.jalali_date }}</td>
                            <td>
                                {% if absence.proof_image %}
                                    <a href="{{ absence.proof_image.url }}" target="_self">
                                        <img src="{% static 'pics/view-icon.png' %}" alt="مشاهده"
                                             class="mx-auto md:w-24 md:h-20 w-8 h-8 opacity-50">
                                    </a>
                                {% else %}
                                    <form method="post" enctype="multipart/form-data"
                                          id="form-{{ absence.attendance_id }}">
                                        {% csrf_token %}
                                        <input type="file" name="proof_{{ absence.attendance_id }}"
                                               accept="image/*"
                                               id="file-{{ absence.attendance_id }}" class="hidden"
                                               onchange="document.getElementById('form-{{ absence.attendance_id }}').submit();">

                                        <label for="file-{{ absence.attendance_id }}" style="cursor: pointer;">
                                            <img src="{% static './pics/upload.png' %}" alt="آپلود"
                                                 class="md:w-20 md:h-20 w-8 h-8 mx-auto">
                                        </label>
                                    </form>
                                {% endif %}
                            </td>
                            <td>
                                {% if absence.proof_verified == True %}
                                    <img src="{% static 'pics/check-green.png' %}" alt="تایید"
                                         class="md:w-14 md:h-14 w-6 h-6 mx-auto">
                                {% elif absence.proof_verified == False %}
                                    <img src="{% static 'pics/check.png' %}" alt="رد"
                                         class="md:w-14 md:h-14 w-6 h-6 mx-auto">
                                {% else %}
                                    <img src="{% static 'pics/check-gray.png' %}" alt="هیج"
                                         class="md:w-14 md:h-14 w-6 h-6 mx-auto">
                                {% endif %}
                            </td>
                        </tr>

                    {% endfor %}
                    </tbody>
                </table>

            </div>

            </div>
        {% elif no_records %}
            <p class="text-center text-gray-500 mt-4">چنین فیلدی وجود ندارد.</p>
        {% endif %}

    </section>

{% endblock content %}